# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, products: List[str]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param products: The products of this InlineResponse2002.  # noqa: E501
        :type products: List[str]
        """
        self.swagger_types = {
            'products': List[str]
        }

        self.attribute_map = {
            'products': 'products'
        }
        self._products = products

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def products(self) -> List[str]:
        """Gets the products of this InlineResponse2002.


        :return: The products of this InlineResponse2002.
        :rtype: List[str]
        """
        return self._products

    @products.setter
    def products(self, products: List[str]):
        """Sets the products of this InlineResponse2002.


        :param products: The products of this InlineResponse2002.
        :type products: List[str]
        """

        self._products = products
