version: "3.9"

services:

  app:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile

    container_name: app_container
    
    ports:
      - "8000:8000"

    hostname: test

    command: python manage.py runserver 0.0.0.0:8000