---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental
  namespace: egs9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
      - name: rental
        image: registry.deti:5000/egs9/rental:15061538
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
  namespace: egs9
spec:
  ports:
  - port: 80
    targetPort: 8002
  selector:
    app: rental
