version: "3.3"
services:
    web:
        # image: rentals_img
        build: .
        ports:
          - "8002:8002"

    mongo:
        image: mongo
        restart: always
    #     environment:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: example

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #       - 8081:8081
    #     environment:
    #       ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #       ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #       ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
