version: '3'
services:
  auth:
    image: authentication_image
    container_name: authentication_container
    build:
      context: ../
      dockerfile: /Dockerfile.dev
    ports:
      - "8001:8001"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/code
  mongo:
    image: mongo
    container_name: mongo_container_auth
    ports:
      - "27019:27017"
    command: mongod --port 27017 --bind_ip 0.0.0.0