# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product_ame: List[str]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param product_ame: The product_ame of this InlineResponse2002.  # noqa: E501
        :type product_ame: List[str]
        """
        self.swagger_types = {
            'product_ame': List[str]
        }

        self.attribute_map = {
            'product_ame': 'product_ame'
        }
        self._product_ame = product_ame

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_ame(self) -> List[str]:
        """Gets the product_ame of this InlineResponse2002.


        :return: The product_ame of this InlineResponse2002.
        :rtype: List[str]
        """
        return self._product_ame

    @product_ame.setter
    def product_ame(self, product_ame: List[str]):
        """Sets the product_ame of this InlineResponse2002.


        :param product_ame: The product_ame of this InlineResponse2002.
        :type product_ame: List[str]
        """

        self._product_ame = product_ame
