FROM python:3.8-alpine

# Add gcc and limits.h
RUN apk add gcc musl-dev 

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /app
COPY src/requirements.txt .

RUN pip install -r requirements.txt

COPY src/webproj/ .

EXPOSE 8003

CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]
