apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stats-pvc
  namespace: egs9
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
