
# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: egs9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: registry.deti:5000/egs9/auth:202206171147  # YYYYMMDDHHmm
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: egs9
spec:
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: auth

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-k3s
  namespace: egs9
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: idp.moviefans.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
