FROM python:3.8-alpine

RUN apk add gcc python3-dev musl-dev libffi-dev

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY src/requirements.txt /usr/src/app/

RUN pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

COPY src/ /usr/src/app

EXPOSE 8001

CMD ["python3", "-m", "swagger_server"]