version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypass
    volumes:
     - ./db/init:/docker-entrypoint-initdb.d
     - ./db/data:/var/lib/mysql
    ports:
     - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

