version: "3"

services:

  web:
    image: statistics_image
    container_name: statistics_container
    build:
      context: ../
      dockerfile: deploy/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8003
    ports:
      - 8003:8003
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypass
    ports:
     - 3306:3306
