FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /app
COPY src/requirements.txt .

RUN pip install -r requirements.txt

COPY docs/ .

RUN python csv_to_mariadb.py

COPY src/webproj/ .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]
