version: "3.3"

services:

  mongo:
        image: mongo
        container_name: mongo_container
        restart: always

  web:
    image: statistics_image
    container_name: statistics_container
    build:
      context: ../
      dockerfile: deploy/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8003
    ports:
      - 8003:8003

  
