FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /app
COPY src/requirements.txt .

RUN pip install -r requirements.txt

COPY src/webproj/ .

CMD ["python", "manage.py", "runserver"]